<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:include filename="$(find rm_description)/urdf/common/swerve_drive.urdf.xacro"/>
    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.42"/>
    <xacro:property name="wheel_base" value="0.42"/>
    <xacro:property name="wheel_offset_z" value="0.06"/>

    <xacro:macro name="chassis">

        <link name="base_link">
            <inertial>
                <mass value="4.947"/>
                <origin xyz="0.012487 0.000034 0.341608"/>
                <inertia ixx="1.617e3" ixy="-3.511e-4" ixz="-2.127e1" iyy="1.616e3" iyz="-1.559e-2" izz="1.723e3"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0285 -0.2685 0.5" rpy="0 0 0"/>
                <geometry>
                    <box size="0.153 0.035 0.040"/>
                </geometry>
            </collision>
        </link>

        <link name="card">
            <inertial>
                <mass value="0.404078"/>
                <origin xyz="0.006702 0.071531 0.019438"/>
                <inertia ixx="3.645e-3" ixy="-2.951e-4" ixz="-8.7675418e-5" iyy="1.235e-3" iyz="-8.535e-4"
                         izz="4.126e-3"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/card.stl"
                          scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
            </collision>
        </link>

        <link name="drag">
            <inertial>
                <mass value="0.404078"/>
                <origin xyz="0.006702 0.071531 0.019438"/>
                <inertia ixx="3.645e-3" ixy="-2.951e-4" ixz="-8.7675418e-5" iyy="1.235e-3" iyz="-8.535e-4"
                         izz="4.126e-3"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/drag.stl"
                          scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
            </collision>
        </link>

        <joint name="drag_joint" type="revolute">
            <parent link="base_link"/>
            <child link="drag"/>
            <origin xyz="-0.245 -0.000076 0.06" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-6.28" upper="6.28" velocity="1" effort="200"/>
        </joint>

        <joint name="card_joint" type="prismatic">
            <parent link="base_link"/>
            <child link="card"/>
            <origin xyz="-0.001 -0.2475 0.005" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-0.1" upper="0.1" velocity="1" effort="200"/>
        </joint>

        <transmission name="trans_card_joint">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="card_joint_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="card_joint">
                <offset>0</offset>
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>

        <transmission name="trans_drag_joint">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="drag_joint_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="drag_joint">
                <offset>0</offset>
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
        </transmission>

        <xacro:swerve_drive prefix="left_front" connected_to="base_link"
                            wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_front" connected_to="base_link"
                            wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="left_back" connected_to="base_link"
                            wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_back" connected_to="base_link"
                            wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>

        <xacro:swerve_transmission prefix="left_front" wheel_reduction="13.733" pivot_offset="0"/>
        <xacro:swerve_transmission prefix="right_front" wheel_reduction="-13.733" pivot_offset="1.861"/>
        <xacro:swerve_transmission prefix="left_back" wheel_reduction="13.733" pivot_offset="1.585"/>
        <xacro:swerve_transmission prefix="right_back" wheel_reduction="-13.733" pivot_offset="6.283"/>

    </xacro:macro>


</robot>
