<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:include filename="$(find rm_description)/urdf/common/swerve_drive.urdf.xacro"/>
    <xacro:property name="wheel_track" value="0.416152"/>
    <xacro:property name="wheel_base" value="0.416152"/>
    <xacro:property name="wheel_offset_z" value="0.06"/>
    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="6.78192"/>
                <origin xyz="-0.010204 -0.005935 0.071865"/>
                <inertia ixx="4.319e-1" ixy="-3.679e-4" ixz="9.099e-3" iyy="2.759e-1" iyz="-2.652e-3" izz="3.458e-1"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/base_link.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0. 0. 0.04" rpy="0 0 0"/>
                <geometry>
                    <box size="0.43 0.602 0.08"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0.125 0.26625 0.3" rpy="0 0 0"/>
                <geometry>
                    <box size="0.04 0.0395 0.44"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0.125 -0.26625 0.3" rpy="0 0 0"/>
                <geometry>
                    <box size="0.04 0.0395 0.44"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.0965 0.27375 0.3" rpy="0 0 0"/>
                <geometry>
                    <box size="0.097 0.0545 0.44"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.0965 -0.27375 0.3" rpy="0 0 0"/>
                <geometry>
                    <box size="0.097 0.0545 0.44"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.013 0.274 0.1055" rpy="0 0 0"/>
                <geometry>
                    <box size="0.07 0.054 0.051"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.013 -0.274 0.1055" rpy="0 0 0"/>
                <geometry>
                    <box size="0.07 0.054 0.051"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0.0285 0.2685 0.5" rpy="0 0 0"/>
                <geometry>
                    <box size="0.153 0.035 0.040"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0.0285 -0.2685 0.5" rpy="0 0 0"/>
                <geometry>
                    <box size="0.153 0.035 0.040"/>
                </geometry>
            </collision>
        </link>

        <joint name="fixed" type="fixed">
            <parent link="base_link"/>
            <child link="base_chassis"/>
            <origin xyz="0. 0. 0.04" rpy="0 0 0"/>
        </joint>

        <link name="base_chassis">
            <inertial>
                <mass value="4.947"/>
                <origin xyz="0.012487 0.000034 0.341608"/>
                <inertia ixx="1.617e3" ixy="-3.511e-4" ixz="-2.127e1" iyy="1.616e3" iyz="-1.559e-2" izz="1.723e3"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/base_chassis.stl"
                          scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0285 -0.2685 0.5" rpy="0 0 0"/>
                <geometry>
                    <box size="0.153 0.035 0.040"/>
                </geometry>
            </collision>
        </link>

        <joint name="jointx" type="prismatic">
            <parent link="base_chassis"/>
            <child link="card"/>
            <origin xyz="-0.2825 -0.001 0.005" rpy="0 0 0"/>
            <axis xyz="1 0 0"/>
            <limit lower="-0.1" upper="0.1" velocity="1" effort="200"/>
        </joint>


        <link name="card">
            <inertial>
                <mass value="0.404078"/>
                <origin xyz="0.006702 0.071531 0.019438"/>
                <inertia ixx="3.645e-3" ixy="-2.951e-4" ixz="-8.7675418e-5" iyy="1.235e-3" iyz="-8.535e-4"
                         izz="4.126e-3"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/card.stl"
                          scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0285 -0.2685 0.5" rpy="0 0 0"/>
                <geometry>
                    <box size="0.153 0.035 0.040"/>
                </geometry>
            </collision>
        </link>

        <joint name="jointx1" type="revolute">
            <parent link="base_chassis"/>
            <child link="hold"/>
            <origin xyz="-0.245 -0.000076 0.06" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-6.28" upper="6.28" velocity="1" effort="200"/>
        </joint>

        <link name="hold">
            <inertial>
                <mass value="0.404078"/>
                <origin xyz="0.006702 0.071531 0.019438"/>
                <inertia ixx="3.645e-3" ixy="-2.951e-4" ixz="-8.7675418e-5" iyy="1.235e-3" iyz="-8.535e-4"
                         izz="4.126e-3"/>
            </inertial>
            <visual>
                <origin xyz="-0.245 -0.000076 0.06" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/engineer/hold.stl"
                          scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0285 -0.2685 0.5" rpy="0 0 0"/>
                <geometry>
                    <box size="0.153 0.035 0.040"/>
                </geometry>
            </collision>
        </link>

        <xacro:swerve_drive prefix="left_front" connected_to="base_chassis"
                            wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_front" connected_to="base_chassis"
                            wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="left_back" connected_to="base_chassis"
                            wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>
        <xacro:swerve_drive prefix="right_back" connected_to="base_chassis"
                            wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                            wheel_z_offset="${wheel_offset_z}"/>


    </xacro:macro>

</robot>
