<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rm_description)/urdf/rmua/friction.urdf.xacro"/>
    <!--    <xacro:include filename="$(find rm_description)/urdf/standard/gimbal.urdf.xacro"/>-->


    <xacro:property name="wheel_offset_x" value="59.188e-3"/>
    <xacro:property name="wheel_offset_y" value="29.25e-3"/>
    <xacro:property name="wheel_offset_z" value="-1.194e-3"/>
    <xacro:property name="offset_y" value="-71e-3"/>


    <xacro:friction_wheel prefixs="left" connected_to="pitch"
                          wheel_x_offset="${wheel_offset_x}" wheel_y_offset="${offset_y+wheel_offset_y}"
                          wheel_z_offset="${wheel_offset_z}"/>

    <xacro:friction_wheel prefixs="right" connected_to="pitch"
                          wheel_x_offset="${wheel_offset_x}" wheel_y_offset="${offset_y-wheel_offset_y}"
                          wheel_z_offset="${wheel_offset_z}"/>


    <link name="trigger">
        <inertial>
            <mass value="63.986e-3"/>
            <origin xyz="0.078e-3 0.135e-3 13.872e-3"/>
            <inertia ixx="30831.483e-9" ixy="-39.921e-9" ixz="-109.832e-9" iyy="30785.507e-9"
                     iyz="-190.34e-9" izz="29863.62e-9"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://rm_description/meshes/rmua/trigger.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://rm_description/meshes/rmua/trigger.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
    </link>

    <joint name="trigger_joint" type="continuous">
        <origin xyz="-0.068 -0.0145 0.0624" rpy="0 0 0"/>
        <dynamics damping="0.0" friction="0.01"/>
        <limit effort="1.0" velocity="43.54" lower="-1e16" upper="1e16"/>
        <parent link="yaw"/>
        <child link="trigger"/>
        <axis xyz="0 0 1 "/>
    </joint>


</robot>
