<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find rm_description)/urdf/common/mecanum_wheel.urdf.xacro"/>

    <!-- https://upload.wikimedia.org/wikipedia/commons/5/52/Wheelbase_and_Track.png -->
    <xacro:property name="wheel_track" value="0.380"/>
    <xacro:property name="wheel_base" value="0.395"/>
    <xacro:property name="wheel_offset_z" value="0.0"/>

    <xacro:macro name="chassis" params="roller_type">

        <link name="base_link">
            <inertial>
                <mass value="1.737"/>
                <origin xyz="0.000425  -0.000733  0.00762"/>
                <inertia ixx="4.088e-2" ixy="9.103e-5" ixz="-1.697e-4" iyy="4.498e-2"
                         iyz="6.472e-5" izz="8.107e-2"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://rm_description/meshes/standard/base.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.580 0.500 0.050"/>
                </geometry>
            </collision>
        </link>

        <xacro:mecanum_wheel prefix="left_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="right_front" connected_to="base_link"
                             wheel_x_offset="${wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="left_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="-1" roller_type="${roller_type}"/>
        <xacro:mecanum_wheel prefix="right_back" connected_to="base_link"
                             wheel_x_offset="${-wheel_track/2}" wheel_y_offset="${-wheel_base/2}"
                             wheel_z_offset="${wheel_offset_z}"
                             reflect="1" roller_type="${roller_type}"/>
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-19.2032"/>
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="19.2032"/>
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-19.2032"/>

    </xacro:macro>

</robot>
